# Generated by Django 2.0.4 on 2018-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181004_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='commit',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(default='', max_length=256, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='支付编号'),
        ),
    ]
